name: Challenge 02
on: push
jobs:
    upload-artifact:
        env:
            artifact_name: "artifact01"
            file_name: "artifact01"
        name: "Upload artifact"
        runs-on: ubuntu-latest
        steps:
            - name: Create a file
              run: touch ${{ env.file_name }}
            - name: Checkout
              uses: actions/checkout@v4.1.1
            - name: Upload a Build Artifact
              uses: actions/upload-artifact@v3.1.3
              with:
                name: ${{ env.artifact_name }}
                path: ./hello_world.txt
        